development:
  adapter: redis
  url: <%= ENV["REDISTOGO_URL"] %>
  channel_prefix: chat_api_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: chat_api_production
