development:
  adapter: redis
  url: <%= ENV["REDISTOGO_URL"] %>
  channel_prefix: chat_api_production

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDISTOGO_URL"] %>
  channel_prefix: chat_api_production
